import { useState, useMemo } from "react";
import {
  BarChart, Bar, LineChart, Line, RadarChart, Radar,
  PolarGrid, PolarAngleAxis, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, ReferenceLine,
} from "recharts";

const C = {
  bg:"#060910", surface:"#0c1220", card:"#101928",
  border:"#182030", borderHi:"#1e3050",
  gold:"#c9a84c", goldDim:"#8a6e2f", goldGlow:"#c9a84c22",
  teal:"#2dd4bf", red:"#f43f5e", amber:"#f59e0b",
  green:"#10b981", blue:"#3b82f6", purple:"#a78bfa",
  t1:"#e8edf5", t2:"#8899bb", t3:"#445577", t4:"#1e2d45",
};

// ─── TRANSLATIONS ─────────────────────────────────────────────────────────────
const T = {
  es: {
    appSubtitle: "MONITOR ANTIMONOPOLIO",
    live: "EN VIVO",
    alerts: "ALERTA",
    alertsPlural: "ALERTAS",
    tabs: ["📊 Dashboard","📉 Comparativa","🔔 Alertas","⚖️ Dictamen IA"],
    filterTitle: "Filtros de Consulta",
    worldRegion: "Región del mundo",
    country: "País",
    territory: "Territorio / Ciudad",
    market: "Mercado",
    product: "Producto / Servicio",
    company: "Empresa",
    dateFrom: "Fecha desde",
    dateTo: "Fecha hasta",
    hourFrom: "Hora desde",
    hourTo: "Hora hasta",
    authority: "AUTORIDAD COMPETENTE",
    legalFrame: "MARCO LEGAL",
    allCompanies: "Todas",
    riskLevel: "Nivel de riesgo",
    marketDispersion: "Dispersión mercado",
    avgVariation: "Variación media",
    maxPrice: "Precio máximo",
    minPrice: "Precio mínimo",
    avgPrice: "Precio promedio",
    betweenCompetitors: "entre competidores",
    vsPrevPeriod: "vs período anterior",
    mostExpensive: "más caro del mercado",
    cheapest: "más barato del mercado",
    marketAvg: "media del mercado",
    score: "Score",
    activeAlerts: "Alertas Activas",
    detection: "detección",
    detections: "detecciones",
    critical: "CRÍTICAS",
    high: "ALTAS",
    medium: "MEDIAS",
    jurisdiction: "JURISDICCIÓN",
    noAlerts: "No se detectaron prácticas restrictivas en el mercado seleccionado. El comportamiento de precios es consistente con competencia normal.",
    notifChannels: "Canales de Notificación",
    emailAlerts: "Correo electrónico",
    active: "Activo",
    alwaysActive: "Siempre activo",
    inAppNotif: "Notificación en app",
    inAppDesc: "Las alertas se actualizan automáticamente al cambiar los filtros.",
    noConfigRequired: "Sin configuración requerida",
    comingSoon: "Próximamente",
    inDevelopment: "En desarrollo",
    detectionThresholds: "Umbrales de Detección",
    activateEmail: "Activar alertas por email",
    configured: "✓ Configurado",
    comparison: "Comparativa entre Competidores",
    rankingTitle: "RANKING DE PRECIOS — menor a mayor",
    average: "Promedio",
    currentVsPrev: "PRECIO ACTUAL vs ANTERIOR",
    deviationVsAvg: "DESVIACIÓN VS PROMEDIO DE MERCADO",
    historicalEvolution: "EVOLUCIÓN HISTÓRICA COMPARADA (7 MESES)",
    riskStats: "Estadísticas de Riesgo Anticompetitivo",
    seeDetail: "Ver detalle →",
    aiAnalysis: "Dictamen Jurídico con IA",
    aiDesc: "La IA genera un dictamen técnico-jurídico basado en los datos del mercado seleccionado, aplicando el marco legal de cada jurisdicción.",
    generateDictum: "⚖️ Generar Dictamen Legal",
    analyzing: "Analizando",
    dictum: "DICTAMEN",
    legalBase: "BASE LEGAL",
    recommendedAction: "ACCIÓN RECOMENDADA",
    applicableSanctions: "SANCIONES APLICABLES",
    severity: "SEVERIDAD",
    probability: "PROBABILIDAD",
    period: "Período",
    schedule: "Horario",
    currentPrice: "Precio actual",
    prevPrice: "Precio anterior",
    variation: "Variación",
    vsAverage: "vs Promedio",
    marketShare: "Cuota mercado",
    changes30: "Cambios 30 días",
    priceAdjustments: "ajustes de precio",
    individualProfile: "Perfil Individual",
    historicalPrice: "EVOLUCIÓN HISTÓRICA DE PRECIO",
    competitiveScore: "SCORECARD COMPETITIVO",
    higherBetter: "Mayor valor = mejor desempeño relativo",
    per: "por",
    prevPeriod: "período anterior",
    marketDeviation: "desviación del mercado",
    estimated: "estimado",
    regions: {
      "América Latina": "América Latina",
      "Europa": "Europa",
      "América del Norte": "América del Norte",
      "Asia": "Asia",
    },
    patternTypes: {
      "FIJACIÓN DE PRECIOS": "FIJACIÓN DE PRECIOS",
      "ALZA SIMULTÁNEA": "ALZA SIMULTÁNEA",
      "PARALELISMO DE PRECIOS": "PARALELISMO DE PRECIOS",
      "POSICIÓN DOMINANTE": "POSICIÓN DOMINANTE",
      "PRECIOS PREDATORIOS": "PRECIOS PREDATORIOS",
      "CONCENTRACIÓN": "CONCENTRACIÓN",
    },
    patternDescs: {
      "FIJACIÓN DE PRECIOS": (v,n) => `Dispersión de solo ${v}% entre ${n} competidores. Coordinación horizontal altamente probable.`,
      "ALZA SIMULTÁNEA": (v) => `Todos los actores incrementaron precios ${v}% simultáneamente. Posible señalización o acuerdo tácito.`,
      "PARALELISMO DE PRECIOS": (v) => `Diferencia máxima entre actores: ${v}%. Comportamiento paralelo sin justificación estructural evidente.`,
      "POSICIÓN DOMINANTE": (c,v) => `${c} concentra el ${v}% del mercado. Posible abuso si impone condiciones desventajosas.`,
      "PRECIOS PREDATORIOS": (c,v) => `${c} vende ${v}% por debajo del promedio. Posible estrategia para excluir rivales.`,
      "CONCENTRACIÓN": (v) => `Las 2 empresas más grandes concentran el ${v}% del mercado. Estructura oligopólica con alto riesgo de coordinación.`,
    },
    patternActions: {
      "FIJACIÓN DE PRECIOS": "Iniciar investigación formal. Solicitar información sobre comunicaciones entre empresas. Revisar actas de gremios.",
      "ALZA SIMULTÁNEA": "Verificar si existieron comunicados de prensa, reuniones gremiales o declaraciones públicas previas al alza.",
      "PARALELISMO DE PRECIOS": "Analizar si la uniformidad obedece a costos homogéneos, regulación tarifaria o factores de mercado legítimos.",
      "POSICIÓN DOMINANTE": "Investigar si impone precios excesivos, condiciona ventas o discrimina clientes sin justificación objetiva.",
      "PRECIOS PREDATORIOS": "Solicitar estructura de costos. Verificar si el precio cubre al menos el costo variable medio.",
      "CONCENTRACIÓN": "Revisar historia de adquisiciones. Evaluar barreras de entrada. Monitorear operaciones de integración futuras.",
    },
    sevLabels: { "CRÍTICA":"CRÍTICA", "ALTA":"ALTA", "MEDIA":"MEDIA" },
    probLabels: {
      high80: "Muy Alta (>80%)",
      high60: "Alta (60-80%)",
      med40: "Media (40-60%)",
      med30: "Media-Alta (50-70%)",
      med35: "Media (35-55%)",
      med30b: "Media (30-50%)",
      med30c: "Media (30-45%)",
    },
    thresholds: [
      "🔴 Fijación de precios — dispersión menor al 0.5%",
      "🟠 Alza simultánea — todos los actores suben más del 10%",
      "🟡 Paralelismo de precios — dispersión entre 0.5% y 2%",
      "🔵 Posición dominante — cuota de mercado superior al 60%",
      "⚡ Precios predatorios — precio menor al 75% del promedio",
      "🔶 Alta concentración — top 2 empresas superan el 80%",
    ],
    aiPrompt: (product, region, country, unit, data, analysis, lf) =>
      `Eres un experto en derecho de la competencia. Analiza los siguientes datos bajo el marco legal de ${country}:\n\nJURISDICCIÓN: ${country}\nAUTORIDAD: ${lf.authority}\nMARCO LEGAL: ${lf.law}\nPRODUCTO: ${product} | TERRITORIO: ${region} | UNIDAD: ${unit}\n\nDATOS:\n${data.map(d=>`- ${d.company}: ${d.price.toLocaleString()} (ant: ${d.prevPrice.toLocaleString()}, var: ${(((d.price-d.prevPrice)/d.prevPrice)*100).toFixed(1)}%, cuota: ${d.marketShare}%)`).join("\n")}\n\nESTADÍSTICAS:\n- Dispersión: ${analysis.variancePct?.toFixed(2)}%\n- Variación: ${analysis.changePct?.toFixed(1)}%\n- Riesgo: ${analysis.risk?.level} (${analysis.risk?.score}/100)\n- Alertas: ${analysis.alerts?.map(a=>a.type).join(", ")||"Ninguna"}\n\nGenera un dictamen técnico-jurídico con: 1) Diagnóstico económico, 2) Prácticas identificadas con artículos exactos, 3) Probabilidad de infracción, 4) Recomendaciones, 5) Sanciones aplicables.`,
    tableHeaders: ["#","EMPRESA","PRECIO","ANTERIOR","VARIACIÓN","vs PROMEDIO","CUOTA","QUEJAS"],
    prev: "Anterior",
    current: "Actual",
    devFromAvg: "Desv. del promedio",
    complaints: "Quejas",
    selected: "seleccionada",
  },
  en: {
    appSubtitle: "ANTITRUST MONITOR",
    live: "LIVE",
    alerts: "ALERT",
    alertsPlural: "ALERTS",
    tabs: ["📊 Dashboard","📉 Comparison","🔔 Alerts","⚖️ AI Legal Opinion"],
    filterTitle: "Query Filters",
    worldRegion: "World Region",
    country: "Country",
    territory: "Territory / City",
    market: "Market",
    product: "Product / Service",
    company: "Company",
    dateFrom: "Date from",
    dateTo: "Date to",
    hourFrom: "Hour from",
    hourTo: "Hour to",
    authority: "COMPETENT AUTHORITY",
    legalFrame: "LEGAL FRAMEWORK",
    allCompanies: "All",
    riskLevel: "Risk level",
    marketDispersion: "Market dispersion",
    avgVariation: "Average variation",
    maxPrice: "Maximum price",
    minPrice: "Minimum price",
    avgPrice: "Average price",
    betweenCompetitors: "between competitors",
    vsPrevPeriod: "vs previous period",
    mostExpensive: "most expensive in market",
    cheapest: "cheapest in market",
    marketAvg: "market average",
    score: "Score",
    activeAlerts: "Active Alerts",
    detection: "detection",
