name: Deploy to Surge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Deploy to Surge
      run: |
        npm install -g surge
        echo ${{ secrets.SURGE_EMAIL }} > ~/.netrc
        echo "machine surge.sh" >> ~/.netrc
        echo "login ${{ secrets.SURGE_EMAIL }}" >> ~/.netrc
        echo "password ${{ secrets.SURGE_TOKEN }}" >> ~/.netrc
        surge --project ./dist --domain fair-compes-app.surge.sh
